# Generated by Django 4.0.2 on 2023-03-01 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='usernames',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='base.perfil'),
        ),
    ]
