# Generated by Django 4.0.2 on 2023-03-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_username_perfil_usernames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='usernames',
            new_name='username',
        ),
    ]
