# Generated by Django 4.0.2 on 2023-03-02 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_usernames_perfil_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='username',
            new_name='usernames',
        ),
    ]
